library/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('authors/', views.authors, name='authors'),
    path('authors/<int:author_id>', views.author, name='author'),
    path('books/', views.BookListView.as_view(), name='books'),
    path('book/', views.RomeoBookListView.as_view(), name='book'),
    path('books/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),
    path('search/', views.search, name='search'),
    path('account/', include('django.contrib.auth.urls')),
    path('mybooks/', views.UserBooksListView.as_view(), name='my-borrowed'),
    path('mybooks2/', views.user_books, name='mybooks2'),
    path('register/', views.register, name='register')
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('library.urls')),
    path('', RedirectView.as_view(url='library/', permanent=False)),
    path('tinymce/', include('tinymce.urls')),
] + (static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) +
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

library/models.py
from django.db import models
import uuid
from django_resized import ResizedImageField
from django.contrib.auth.models import User
from datetime import date
from tinymce.models import HTMLField

# help_text labiau adminui
class Genre(models.Model):
    genre_id = models.AutoField(primary_key=True)
    name = models.CharField('Name', max_length=100, help_text="enter type of genre: ")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Genre'
        verbose_name_plural = 'Genres'

class Author(models.Model):
    author_id = models.AutoField(primary_key = True)
    first_name = models.CharField("First name", max_length=100)
    last_name = models.CharField("Last name", max_length=100)
    description = HTMLField(null=True)
    class Meta:
        ordering = ['last_name', 'first_name']

    def __str__(self):
        return f"{self.first_name} - {self.last_name}"

    def display_books(self):
        return ', '.join(book.title for book in self.books.all())

class Book(models.Model):
    book_id=models.AutoField(primary_key=True)
    author = models.ForeignKey(Author, on_delete=models.SET_NULL, null=True, related_name='books')
    title = models.CharField('Title', max_length=200, help_text="enter book title: ")
    description = models.TextField('Description', max_length=1000, help_text="enter book description: ")
    isbn = models.CharField(
        'ISBN', max_length=13,
        help_text='ISBN nr.: <a href="https://www.isbn-international.org/content/what-isbn">ISBN kodas</a>'
    )
    genre = models.ManyToManyField(Genre, help_text="Enter book genre: ")
    cover = ResizedImageField('Viršelis',size=[300,400],upload_to='covers',null=True)



    def __str__(self):
        return self.title

    def display_genre(self):
        return ', '.join(genre.name for genre in self.genre.all())


class Bookinstance(models.Model):
    instance_id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text = 'Unique book UUID code')
    book = models.ForeignKey(Book, on_delete=models.SET_NULL, null=True)
    due_back = models.DateField("Available", null = True, blank = True)
    reader = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    LOAN_STATUS = (("p", "Processing"),
    ("t", "Taken"),
    ("a", "Available"),
    ("r", "Reserved"))

    book_status = models.CharField(max_length=1, default='a', blank=True, choices=LOAN_STATUS, help_text="Book status")
    @property
    def is_overdue(self):
        if date.today() > self.due_back:
            return True
        return False

    class Meta:
        ordering = ['due_back']

    def __str__(self):
        return f'{self.book.title}'


class BookReview(models.Model):
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True, blank=True, related_name='review')
    reviewer = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True)
    content = models.TextField('Atsiliepimas', max_length=2000)

    class Meta:
        verbose_name = "Atsiliepimas"
        verbose_name_plural = 'Atsiliepimai'
        ordering = ['-date_created']

library/forms.py
from .models import BookReview
from django import forms

class BookReviewForm(forms.ModelForm):
    class Meta:
        model = BookReview
        fields = ('content', 'book', 'reviewer',)
        widgets = {'book': forms.HiddenInput(), 'reviewer': forms.HiddenInput()}

library/views.py
from django.shortcuts import render, get_object_or_404, reverse
# from django.http import HttpResponse
from .models import Book, Author, Bookinstance, Genre
from django.views import generic
from django.core.paginator import Paginator
from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from django.contrib.auth.forms import User
from django.views.decorators.csrf import csrf_protect
from django.contrib import messages
from .forms import BookReviewForm
# Importuojame FormMixin, kurį naudosime BookDetailView klasėje
from django.views.generic.edit import FormMixin

def index(request):
    num_books = Book.objects.all().count()
    num_books1 = Book.objects.filter(title__exact='Steve Jobs').count()
    num_instances = Bookinstance.objects.all().count()
    num_instances_available = Bookinstance.objects.filter(book_status__exact='a').count()
    num_authors = Author.objects.count()

    num_visits = request.session.get('num_visits', 1)
    request.session['num_visits'] = num_visits + 1
    context = {
        'num_books': num_books,
        'num_books1':num_books1,
        'num_instances': num_instances,
        'num_instances_available': num_instances_available,
        'num_authors': num_authors,
        'num_visits': num_visits,
    }

    # renderiname index.html, su duomenimis kintamąjame context
    return render(request, 'index.html', context=context)


def authors(request):
    paginator = Paginator(Author.objects.all(), 2)
    page_number = request.GET.get('page')
    paged_authors = paginator.get_page(page_number)
    context = {
        'authors': paged_authors
    }
    return render(request, 'authors.html', context=context)

def author(request, author_id):
    single_author = get_object_or_404(Author, pk=author_id)
    return render(request, 'author.html', {'author': single_author})





# class based approach to create views

class BookListView(generic.ListView):
    model = Book
    paginate_by = 3
    template_name = 'book_list.html'


class RomeoBookListView(generic.ListView):
    model = Book
    context_object_name = 'my_book_list'
    queryset = Book.objects.filter(title__icontains='Romeo')[:3]
    template_name = 'romeo_list.html'






class BookDetailView(FormMixin, generic.DetailView):
    model = Book
    template_name = 'book_detail.html'
    form_class = BookReviewForm

    # nurodome, kur atsidursime komentaro sėkmės atveju.
    def get_success_url(self):
        return reverse('book-detail', kwargs={'pk': self.object.book_id})

    # standartinis post metodo perrašymas, naudojant FormMixin, galite kopijuoti tiesiai į savo projektą.
    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    # štai čia nurodome, kad knyga bus būtent ta, po kuria komentuojame, o vartotojas bus tas, kuris yra prisijungęs.
    def form_valid(self, form):
        form.instance.book = self.object
        form.instance.reviewer = self.request.user
        form.save()
        return super(BookDetailView, self).form_valid(form)




def search(request):
    """
    paprasta paieška. query ima informaciją iš paieškos laukelio,
    search_results prafiltruoja pagal įvestą tekstą knygų pavadinimus ir aprašymus.
    Icontains nuo contains skiriasi tuo, kad icontains ignoruoja ar raidės
    didžiosios/mažosios.
    """
    query = request.GET.get('query')
    search_results = Book.objects.filter(Q(title__icontains=query) | Q(description__icontains=query) |
                                         Q(author__first_name__icontains=query) )
    return render(request, 'search.html', {'books': search_results, 'query': query})





class UserBooksListView(LoginRequiredMixin, generic.ListView):
    model = Bookinstance
    template_name = 'user_books.html'
    paginate_by = 2

    def get_queryset(self):
        return Bookinstance.objects.filter(reader=self.request.user).filter(book_status__exact='t').order_by('due_back')


@login_required(login_url='login')
def user_books(request):
    user = request.user
    try:
        user_books = Bookinstance.objects.filter(reader=request.user).filter(book_status__exact='t').order_by('due_back')
    except Bookinstance.DoesNotExist:
        user_books = None
    context = {
        'user': user,
        'user_books': user_books,
    }
    return render(request, 'user_books1.html', context=context)

@csrf_protect
def register(request):
    if request.method == "POST":
        # taking from user form:
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        password2 = request.POST['password2']
        # checkai:
        # if passwords not match rise message
        if password != password2:
            messages.error(request, 'Slaptažodžiai nesutampa!')
            return redirect('register')
        # if user already exists rise message
        if User.objects.filter(username=username).exists():
            messages.error(request, f'Vartotojo vardas {username} užimtas!')
            return redirect('register')
        # if email already exists rise message
        if User.objects.filter(email=email).exists():
            messages.error(request, f'Vartotojas su el. paštu {email} jau užregistruotas!')
            return redirect('register')

        # if above checks pass, create new user
        User.objects.create_user(username=username, first_name=first_name, last_name=last_name, email=email, password=password)
        messages.info(request, f'Vartotojas {username} užregistruotas!')
        return redirect('login')

    return render(request, 'registration/register.html')

library/templates/author.html
{% extends "base.html" %}

{% block content %}
    <div class="container author">
    <h4>{{ author.first_name }} {{ author.last_name }}</h4>
    <hr/>
    <p>{{ author.description | safe }}</p>
    </hr>
    </br>
    <h5>We have these {{ author.first_name }} {{ author.last_name }} books:</h5>
    {% for i in author.books.all %}
       <li>{{ i.title }}</li>
    {% endfor %}
    </div>
{% endblock %}

library/templates/authors.html
{% extends "base.html" %}

{% block content %}
  <h1>Authors</h1>
  <p>Our books list:</p>
  {% for a in authors %}
    <li><a href="{% url 'author' a.author_id %}">{{a.first_name}} {{a.last_name}}</a></li>
  {% endfor %}
<div class="container puslapiai">
    <nav aria-label="...">
        {% if authors.has_other_pages %}
            <ul class="pagination pagination-sm justify-content-center">
                {% for i in authors.paginator.page_range %}
                    {% if authors.number == i %}
                        <li class="page-item active">
                            <a class="page-link">{{ i }}</a>
                        </li>
                    {% else %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                        </li>
                    {% endif %}
                {% endfor %}
            </ul>
        {% endif %}
    </nav>
</div>
{% endblock %}

library/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>Biblioteka</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">
        {% block sidebar %}
          <ul class="sidebar-nav">
            {% if user.is_authenticated %}
            <li><a href="{% url 'index' %}">Home</a></li>
            <li><a href="{% url 'books' %}">Books</a></li>
            <li><a href="{% url 'book' %}">Romeo</a></li>
            <li><a href="{% url 'authors' %}">Authors</a></li>
            <li><a href="{% url 'my-borrowed'%}">My Books</a></li>
            <li><a href="{% url 'mybooks2'%}">My Books2</a></li>
            <br>
              <li>
                <form action="{% url 'search' %}" method="get" class="form-inline my-2 my-md-0">
                   <input name="query" class="form-control-sm-info" style="width:100px" type="text" placeholder="Search">
                </form>
              </li>
            <li><a href="{% url 'logout' %}">Logout {{ user.first_name }}</a></li>
            {% else %}
            <li><a href="{% url 'login' %}">Login</a></li>
            <li><a href="{% url 'register' %}">Register</a></li>
          </ul>
        {% endif %}
       {% endblock %}
      </div>
      <div class="col-sm-10 ">
        {% if messages %}
    {% for message in messages %}
        <div class="alert alert-{% if message.tags == 'error' %}danger{% elif message.tags == 'info' %}success{% endif %}" role="alert">
        {{ message }}
        </div>
    {% endfor %}
{% endif %}
        {% block content %}{% endblock %}</div>
    </div>
  </div>
</body>
</html>

library/templates/book_detail.html
{% extends "base.html" %}

{% block content %}
 {% load static %}
  {% if book.cover %}
    <img src="{{ book.cover.url }}" class="card-img-top book-cover" alt="..." style="margin-top: 60px, margin-bottom: 20px">
            {% else %}
    <img src="{% static 'media/covers/no-image.png' %}" class="card-img-top book-cover" style="margin-top: 60px, margin-bottom: 20px">
  {% endif %}

  <h1>{{ book.title }}</h1>

  <p><strong>Autorius:</strong> <a href="{% url 'author' book.author.pk %}">{{ book.author }}</a></p>
  <p><strong>Aprašymas:</strong> {{ book.description }}</p>
  <p><strong>ISBN:</strong> {{ book.isbn }}</p> 
  <p><strong>Žanras:</strong> {{ book.genre.all|join:", " }}</p>  

  <div style="margin-left:20px;margin-top:20px">
    <h4>Kopijos:</h4>

    {% for copy in book.bookinstance_set.all %}
      <hr>
      <p class="{% if copy.book_status == 'a' %}text-success{% elif copy.book_status == 'm' %}text-danger{% else %}text-warning{% endif %}">
        {{ copy.get_book_status_display }}
      </p>
      {% if copy.book_status != 'a' %}
        <p><strong>Bus grąžinta:</strong> {{ copy.due_back }}</p>
      {% endif %}
      <p class="text-muted"><strong>Id:</strong> {{ copy.instance_id }}</p>
    {% endfor %}
  </div>

</br>
  <h4>Atsiliepimai:</h4>
  {% if book.review.all %}
    {% for review in book.review.all %}
      <hr>
      <strong>{{ review.reviewer }}</strong>, <em>{{ review.date_created}}</em>
      <p>{{ review.content }}</p>
    {% endfor %}
  {% else %}
    <p>Knyga neturi atsiliepimų</p>
  {% endif %}

  {% if user.is_authenticated %}
  <div class="fieldWrapper">
    <hr><br/>
    <h4>Palikite atsiliepimą:</h4>
    <form action="" method="post">
      {% csrf_token %}
      {{ form.content }}</br>
      <input type="submit" value="Išsaugoti">
    </form>
  </div>
  {% endif %}

{% endblock %}

library/templates/book_list.html
{% extends "base.html" %}

{% block content %}

 {% load static %}
    <h1>Book list</h1></br>
    {% if object_list %}
    <div class="row">
      {% for book in object_list %}
        <div class="col-md-4 d-flex align-items-stretch">
          <div class="card mb-4 shadow-sm " >
            {% if book.cover %}
              <img src="{{ book.cover.url }}" class="card-img-top book-cover" alt="..." >
            {% else %}
              <img src="{% static 'media/covers/no-image.png' %}" class="card-img-top book-cover">
            {% endif %}
            <div class="card-body">
              <h6 class="card-subtitle mb-2 text-muted">{{ book.author }}</h6>
              <p class="card-text"><a href="{{ book.book_id }}">{{ book.title }}</a></p>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
    {% else %}
      <p>There are no books.</p>
    {% endif %}




  <div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">back</a>
        {% endif %}

        <span class="current">
            {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
{% endblock %}

library/templates/index.html
{% extends "base.html" %}

{% block content %}
  <h1>Region library</h1>
  <p>Hello to our virtual library</p>
  <p>Statistics:</p>
  <ul>
    <li><strong>Total book count:</strong> {{ num_books }}</li>
    <li><strong>Steve Jobs book count:</strong> {{ num_books1 }}</li>
    <li><strong>number of exemplaries:</strong> {{ num_instances }}</li>
    <li><strong>Free exemplaries:</strong> {{ num_instances_available }}</li>
    <li><strong>Authors count:</strong> {{ num_authors }}</li>
  </ul>

<p>Čia jūs lankotes {{ num_visits }}-ą kartą.</p>
{% endblock %}

library/templates/romeo_list.html
{% extends "base.html" %}

{% block content %}
  <h1>Romeo books list:</h1>
  {% if my_book_list %}
  <ul>
    {% for book in my_book_list %}
      <li>
        <a href="{{ book.id }}">{{ book.title }}</a> ({{book.author}})
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>We do not have any books</p>
  {% endif %}
{% endblock %}

library/templates/search.html
{% extends "base.html" %}

{% block content %}
  <h1>Paieškos pagal "{{query}}" rezultatai:</h1>
  </br>
  {% if books %}
  <ul>
    {% for book in books %}
      <li>
        <a href="{% url 'book-detail' book.book_id %}">{{ book.title }}</a> ({{book.author}})
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>Oops. Nieko neradome :(</p>
  {% endif %}

  {% endblock %}

library/templates/user_books.html
{% extends "base.html" %}

{% block content %}
    <h1>My taken books</h1>

    {% if bookinstance_list %}
    <ul>

      {% for bookinst in bookinstance_list %} 
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a> ({{ bookinst.due_back }})        
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>Šiuo metu iš mūsų nesate paėmę knygų.</p>
    {% endif %}       
{% endblock %}

library/templates/user_books1.html
{% extends "base.html" %}

{% block content %}
<h1>{{user.first_name}} {{user.last_name}} taken books</h1>


    {% if user_books %}
    <ul>

      {% for book in user_books %}
      <li class="{% if book.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' book.book.pk %}">{{book.book.title}}</a> ({{ book.due_back }})
      </li>
      {% endfor %}
    </ul>


    {% endif %}       
{% endblock %}